### ISSUE TITLE
unique constraint not working

### ISSUE THREAD

**Issue by bp-FLN** [grails/grails-data-mapping#1278]
While upgrading from grails 3.1.15 to 3.3.11 we noticed a regression on the unique constraint.
More specifically, a multi-column unique constraint on the same domain class.

We noticed that the query for the unique check is incomplete:
`select this_.id as y0_ from domain this_ where this_.identifier=? limit ?`
the parent is not even considered

This used to work in grails 3.1.15 which generates this query instead:
`select this_.id as id1_0_0_, this_.version as version2_0_0_, this_.identifier as identifi3_0_0_, this_.is_parent as is_paren4_0_0_, this_.parent_id as parent_i5_0_0_ from domain this_ where this_.identifier=? and this_.parent_id=?`

The sample project has an integration test that showcases this.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the sample repo and run `DomainIntegrationTest`
2. last test fails

### Expected Behaviour

spec should not fail

### Actual Behaviour

spec fails - the unique constraint in the Domain class is not working as expected

### Environment Information

- **Operating System**: MacOS 10.14.6
- **GORM Version:** 6.1.12.RELEASE
- **Grails Version (if using Grails):** 3.3.11
- **JDK Version:** openjdk version "1.8.0_232"

### Example Application

https://github.com/bp-FLN/uniqueConstraint/

**Comment by jameskleeh** [comment]
This should be fixed in GORM 7.0.2

**Comment by bp-FLN** [comment]
@jameskleeh i tried GORM 7.0.2 but can't make it work. i always get this exception:
```java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.DefaultGroovyMethods.collect([Ljava/lang/Object;Lgroovy/lang/Closure;)Ljava/util/List;
	at grails.plugin.hibernate.HibernateGrailsPlugin.doWithSpring_closure1(HibernateGrailsPlugin.groovy:65)```

**Comment by jameskleeh** [comment]
Right it requires the new spring version that is used in grails 4

**Comment by bp-FLN** [comment]
unfortunately, we can't upgrade to grails 4 yet and have to stick with grails 3.3.x.
is there any chance that this fix gets backported to GORM 6.x? or is there some workaround instead?
