### ISSUE TITLE
6.1.3 - hibernate-5.1 vs. hibernate-5.2 once again: NoSuchMethodError EntityPersister.findDirty

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#947]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. use gorm-6.1.3 with `hibernate.hibernateDirtyChecking: true` (not sure if the latter one matters)
2. invoke `isDirty()` on an entity
3. exception

change was introduced by 59c4f397477e5c3cc4bbc01954adf848df7075a2 fixing grails/grails-core#10613

this is yet another breaking change from hibernate-5.1.x to hibernate-5.2.x :(
`EntityPersister.findDirty(..., SessionImplementor)` signature changed to `EntityPersister.findDirty(..., SharedSessionContractImplementor)`

* https://github.com/hibernate/hibernate-orm/blob/5.1.6/hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java#L250
* https://github.com/hibernate/hibernate-orm/blob/5.2.10/hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java#L250

n.b. i already upvoted #942 ;)

### Expected Behaviour

`notThrown Exception`

### Actual Behaviour

```
java.lang.NoSuchMethodError: org.hibernate.persister.entity.EntityPersister.findDirty([Ljava/lang/Object;[Ljava/lang/Object;Ljava/lang/Object;Lorg/hibernate/engine/spi/SessionImplementor;)[I
	at org.grails.orm.hibernate.HibernateGormInstanceApi.isDirty(HibernateGormInstanceApi.groovy:83)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.isDirty(GormEntity.groovy:223)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$isDirty$7.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at myapp.MyDomain.isDirty(MyDomain.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Environment Information

- **Operating System**: win x64
- **GORM Version:** 6.1.3
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** oracle 8u112

### Example Application

n/a

**Comment by derKasi** [comment]
I think there must also be an fix of:
`int[] dirtyPropertyIndexes = persister.findDirty(currentState, entry.loadedState, instance, session)`
in the Method
` List getDirtyPropertyNames(D instance)`
