### ISSUE TITLE
GPMONGODB-361: 2.0.0 broke embedded collections of documents

### ISSUE THREAD

**Issue by graemerocher** [grails/grails-data-mapping#409]
Original Reporter: jgibson
Environment: Grails 2.3.7 and MongoDB plugin 2.0.0
Version: 2.0.0.GA
Migrated From: http://jira.grails.org/browse/GPMONGODB-361

After upgrading to MongoDB plugin version 2.0.0 from 1.3.3 I discovered that my objects that contained embedded collections could not be loaded. I know that the plugin is working for other objects because my Spring Security-based login is OK.

Here is the error:
{noformat}
Caused by NoSuchMethodError: 
org.grails.datastore.mapping.mongo.engine.MongoEntityPersister.createEmbeddedKey(Ljava/lang/Object;)Ljava/lang/String;
->>  212 | loadEmbeddedCollection in org.grails.datastore.mapping.mongo.engine.MongoEntityPersister

---

|    502 | refreshObjectStateFromNativeEntry in org.grails.datastore.mapping.engine.NativeEntryEntityPersister
|    116 | refreshObjectStateFromNativeEntry in org.grails.datastore.mapping.mongo.engine.MongoEntityPersister
|     82 | refreshObjectStateFromNativeEntry in     ''
|    383 | createObjectFromNativeEntry in org.grails.datastore.mapping.engine.NativeEntryEntityPersister
|   1345 | convertDBObject in org.grails.datastore.mapping.mongo.query.MongoQuery$MongoResultList
|   1319 | next . .  in org.grails.datastore.mapping.mongo.query.MongoQuery$MongoResultList$1
|    264 | retrieveAllEntities in org.grails.datastore.mapping.mongo.engine.MongoEntityPersister
|    167 | retrieveAll in org.grails.datastore.mapping.engine.EntityPersister
|    738 | retrieveAll in org.grails.datastore.mapping.core.AbstractSession
|    214 | initialize in org.grails.datastore.mapping.collection.AbstractPersistentCollection
|     90 | size      in     ''
|     21 | doCall .  in IndexController.groovy
|     53 | doFilter  in GrailsAnonymousAuthenticationFilter.java
|     49 | doFilter  in RequestHolderAuthenticationFilter.java
|     82 | doFilter  in MutableLogoutFilter.java
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run . . . in java.lang.Thread
{noformat}

Here are the object definitions, in case they're the problem.
{code:Java}
class SavedQuery {
  Person person
  String name
  boolean shared = false
  List<QueryParameter> queryParameters
  List<QueryParameter> clientParameters
  Date dateCreated
  Date lastUpdated

  public int queryHashCode() {
    return queryParameters == null || queryParameters.empty ? 0 : Arrays.hashCode(queryParameters.toArray())
  }

  static embedded = ['queryParameters', 'clientParameters']
  static constraints = {
    person nullable: false, unique: 'name'
    name nullable: false
    queryParameters nullable: false
    clientParameters nullable: false
  }
  static mapping = {
    person column: 'person_id'
    queryParameters lazy: false
    clientParameters lazy: false
  }
}
{code}

{code:Java}
class QueryParameter {
  String name
  List<String> values

  static embedded = ['values']
  static constraints = {
    name nullable: false
    values nullable: false
  }

  String toString() {
    return "Param: ${name}=${values}"
  }
}
{code}
