### ISSUE TITLE
excuteQuery does not work with Hibernate 5.2

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-data-mapping#924]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application with Grails 3.2.9, GORM 6.1.2 and Hibernate 5.2.10.Final.
2. Create domain `Book`.
3. Execute `Book.executeQuery` in test.

```groovy
package test.web

import grails.test.mixin.TestFor
import grails.test.hibernate.HibernateSpec

@TestFor(Book)
class BookSpec extends HibernateSpec {

    def setup() {
    	new Book(title: 'book1').save()
    	new Book(title: 'book2').save()
    }

    def cleanup() {
    }

    void "test count"() {
        expect:"count equals 2"
            Book.count() == 2
    }

    void "test find"() {
    	expect:
            Book.findByTitle('book1').title == 'book1'
    }

    void "test executeQuery"() {
    	expect:
            Book.executeQuery('from Book').size() == 2
    }
}
```

4. Test failed. 

### Expected Behaviour

Pass the test as Hibernate 5.1.5.Final.

### Actual Behaviour

Test report has following exception:

```
java.lang.NoSuchMethodError: org.hibernate.SharedSessionContract.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery_closure15(AbstractHibernateGormStaticApi.groovy:580)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery(AbstractHibernateGormStaticApi.groovy:579)
	at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1013)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery(AbstractHibernateGormStaticApi.groovy:397)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.executeQuery(GormEntity.groovy:1017)
	at test.web.BookSpec.test executeQuery(BookSpec.groovy:31)
```

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.2
- **Hibernate Version:** 5.2.10.Final
- **Grails Version (if using Grails):** 3.2.9
- **JDK Version:** 1.8
