### ISSUE TITLE
Grails 3.2.9; Gorm 6.1.2; Hibernate 5.2.10 java.lang.NoSuchMethodError: org.hibernate.SharedSessionContract.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-data-mapping#931]
Here is my domain class
```
class Post implements AsyncEntity<Post> {
         // leave out other fields
	Status status = Status.NEW

	enum Status {
		NEW, APPROVED, DECLINED, OUTDATED, DUPLICATED, INVALID
	}
}
```

Here is my service method: 
```
Map<Post.Status, Integer> countByStatus() {
	Post.executeQuery('select status, count(*) from Post group by status').collectEntries { [it[0], it[1]] }
}

```
This working fine with hibernate 5.1.x, but after upadting to hibernate 5.2.x I've got such an exception:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - NoSuchMethodError occurred when processing request: [GET] /posts/stats
org.hibernate.SharedSessionContract.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.hibernate.SharedSessionContract.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi$_executeQuery_closure15.doCall(AbstractHibernateGormStaticApi.groovy:580)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery(AbstractHibernateGormStaticApi.groovy:579)
	at org.grails.datastore.gorm.GormStaticApi.executeQuery(GormStaticApi.groovy:1013)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery(AbstractHibernateGormStaticApi.groovy:397)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.executeQuery(GormEntity.groovy:1017)
	at org.example.PostStatsService.$tt__countByStatus(PostStatsService.groovy:23)
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	... 3 common frames omitted

```

- Windows 10
- GORM Version: 6.1.2
- Grails Version: 3.2.9
- Hibernate Version: 5.2.10
- JDK Version: 1.8.0_131 (Oracle Corporation 25.131-b11)
